name: Amazon Linux CI

on: [push]  # Trigger the workflow every time you push to the repo

jobs:
  amazonlinux-job:
    runs-on: ubuntu-latest  # GitHub VM host
    container: amazonlinux:2  # Your job runs inside Amazon Linux 2 container

    steps:
      - name: Install Git and Bash
        run: |
          # Install tools that Amazon Linux base image does not have
          yum install -y git bash

          # Confirm they were installed
          git --version
          bash --version

      - name: Manually Clone the Repo
        run: |
          # Use GitHub-provided environment variable to get the repo name
          git clone https://github.com/${{ github.repository }} .

      - name: Run the hello.sh script
        run: |
          bash hello.sh
